baseurl      = "https://untilthecore.github.io/"
title        = "My Blog"
languageCode = "zh-Hans"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "You can get what you want."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

# Social icons

  [[params.social]]
    name = "email"
    url  = "mailto:untilthecore@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/UntilTheCore"


[languages]
  [languages.en]
    title = "Welcome"
    subtitle = "My frinends"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "UntilTheCore"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blogs"
    url        = "/posts"
  [[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
